"""initial schema

Revision ID: d2297a0afccd
Revises: 
Create Date: 2026-07-28 11:35:14.976146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2297a0afccd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('name', name=op.f('uq_leagues_name'))
    )
    op.create_table('user_profiles',
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('PLAYER', 'CLUB_ADMIN', 'LEAGUE_COORDINATOR', 'FEDERATION_ADMIN', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('auth_user_id', name=op.f('uq_user_profiles_auth_user_id'))
    )
    op.create_table('audit_logs',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name=op.f('fk_audit_logs_user_profile_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('clubs',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_clubs_league_id_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs')),
    sa.UniqueConstraint('league_id', 'name', name='uq_league_club_name')
    )
    op.create_index('ix_club_name', 'clubs', ['name'], unique=False)
    op.create_table('notifications',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name=op.f('fk_notifications_user_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notification_user', 'notifications', ['user_profile_id'], unique=False)
    op.create_table('players',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('federation_id', sa.String(length=50), nullable=True),
    sa.Column('fide_id', sa.String(length=50), nullable=True),
    sa.Column('chesscom_username', sa.String(length=100), nullable=True),
    sa.Column('lichess_username', sa.String(length=100), nullable=True),
    sa.Column('rapid_rating', sa.Integer(), nullable=True),
    sa.Column('blitz_rating', sa.Integer(), nullable=True),
    sa.Column('classical_rating', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name=op.f('fk_players_user_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('user_profile_id', name=op.f('uq_players_user_profile_id'))
    )
    op.create_index('ix_player_chesscom', 'players', ['chesscom_username'], unique=False)
    op.create_index('ix_player_fide', 'players', ['fide_id'], unique=False)
    op.create_index('ix_player_lichess', 'players', ['lichess_username'], unique=False)
    op.create_table('seasons',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('registration_open', sa.Boolean(), nullable=False),
    sa.Column('transfers_open', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_seasons_league_id_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('league_id', 'year', name='uq_league_year')
    )
    op.create_table('club_members',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_members_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name=op.f('fk_club_members_user_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_members')),
    sa.UniqueConstraint('club_id', 'user_profile_id', name='uq_club_member')
    )
    op.create_table('registrations',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='registrationstatus'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_registrations_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_registrations_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_registrations_season_id_seasons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registrations')),
    sa.UniqueConstraint('player_id', 'season_id', name='uq_player_season_registration')
    )
    op.create_index('ix_registration_club', 'registrations', ['club_id'], unique=False)
    op.create_index('ix_registration_player', 'registrations', ['player_id'], unique=False)
    op.create_table('transfers',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('from_club_id', sa.UUID(), nullable=False),
    sa.Column('to_club_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='transferstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_club_id'], ['clubs.id'], name=op.f('fk_transfers_from_club_id_clubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_transfers_registration_id_registrations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_club_id'], ['clubs.id'], name=op.f('fk_transfers_to_club_id_clubs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers'))
    )
    op.create_index('ix_transfer_status', 'transfers', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_documents_transfer_id_transfers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_profiles.id'], name=op.f('fk_documents_uploaded_by_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_table('transfer_approvals',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='approvaldecision'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user_profiles.id'], name=op.f('fk_transfer_approvals_approved_by_user_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_transfer_approvals_transfer_id_transfers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_approvals'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_approvals')
    op.drop_table('documents')
    op.drop_index('ix_transfer_status', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('ix_registration_player', table_name='registrations')
    op.drop_index('ix_registration_club', table_name='registrations')
    op.drop_table('registrations')
    op.drop_table('club_members')
    op.drop_table('seasons')
    op.drop_index('ix_player_lichess', table_name='players')
    op.drop_index('ix_player_fide', table_name='players')
    op.drop_index('ix_player_chesscom', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_notification_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_club_name', table_name='clubs')
    op.drop_table('clubs')
    op.drop_table('audit_logs')
    op.drop_table('user_profiles')
    op.drop_table('leagues')
    # ### end Alembic commands ###
